# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
codecov: true

env:

script: # the default script is equivalent to the following
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/RedPointyJackson/Brooglie.git"))'
 - julia -e 'using Pkg; Pkg.build();'
 - julia -e 'using Pkg; Pkg.test("CarrierCapture"; coverage=true)';

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("CarrierCapture")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
